# Generated by Django 4.2.2 on 2023-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmission',
            name='QuestId',
            field=models.IntegerField(),
        ),
    ]
